name: build_document

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - 'generated/**'

env:
  RESULT_PATH: ./generated
  PYTHON_VERSION: 3.8

jobs:
  build:
    runs-on: ubuntu-20.04
    timeout-minutes: 60

    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{secrets.PUSH_TOKEN}}
    - name: Install dependencies
      run: |
        sudo apt-get install texlive-latex-extra
        sudo apt-get install cm-super
        sudo apt-get install texlive-lang-polish
        sudo apt-get install texlive-fonts-extra
        sudo apt-get install dvipng
    - name: Set up Python ${{env.PYTHON_VERSION}}
      uses: actions/setup-python@v2
      with:
        python-version: ${{env.PYTHON_VERSION}}
    - name: Install python dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install matplotlib
    - name: run build script
      working-directory: ${{github.workspace}}
      shell: bash
      run: |
        ./ubuntu_local_par_build.sh
        mkdir -p ${{env.RESULT_PATH}}
        mv ./latex/pi2021.pdf ${{env.RESULT_PATH}}
    - name: status at ${{github.ref}}
      run: git status
    - name: commit and push result
      working-directory: ${{github.workspace}}
      shell: bash
      run: |
        git config --global user.name 'build_document_action'
        git config --global user.email 'vil02@users.noreply.github.com'
        git add ${{env.RESULT_PATH}}
        git commit -m "Automated document generation"
        git push
