name: Check Markdown links

on:
  workflow_dispatch:
  push:
    branches: [master]
  schedule:
    - cron: '10 */3 * * *'

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: gaurav-nelson/github-action-markdown-link-check@v1
      with:
        use-quiet-mode: 'yes'
