---
name: python_test

# yamllint disable-line rule:truthy
on:
  workflow_dispatch:
  push:
    paths-ignore:
      - 'generated/**'
  schedule:
    - cron: '0 */6 * * *'

jobs:
  python_test:
    runs-on: ${{matrix.os}}
    timeout-minutes: 8
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-18.04
          - ubuntu-20.04
          - macos-10.15
          - macos-11
          - windows-2016
          - windows-2019
          - windows-2022
        python-version: [3.7, 3.8, 3.9, 3.10-dev]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python ${{matrix.python-version}}
        uses: actions/setup-python@v2
        with:
          python-version: ${{matrix.python-version}}
      - name: Install dependencies
        shell: bash
        run: |
          python -m pip install --upgrade pip
          python -m pip install flake8 pylint pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Run linter
        shell: bash
        run: |
          cd python/
          ./check_all_python_scripts.sh
      - name: Test with pytest
        run: |
          pytest
...
