name: python_test

on:
  push:
    branches: [master]
    paths-ignore:
      - 'generated/**'    

jobs:
  build:
    runs-on: ${{matrix.os}}
    timeout-minutes: 2
    strategy:
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04]
        python-version: [3.7, 3.8, 3.9, 3.10-dev]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{matrix.python-version}}
      uses: actions/setup-python@v2
      with:
        python-version: ${{matrix.python-version}}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        flake8 . --count --max-line-length=80 --statistics --show-source
    - name: Test with pytest
      run: |
        pytest
